# Generated by Django 2.0 on 2018-05-27 02:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpectedIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expectedindex', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IndexSwap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myindex', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='expectedindex',
            name='index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.IndexSwap'),
        ),
    ]
