# Generated by Django 2.0 on 2018-05-27 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0002_auto_20180527_0236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myindex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.CharField(max_length=10)),
                ('views', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='expectedindex',
            name='index',
        ),
        migrations.AddField(
            model_name='expectedindex',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expectedindex',
            name='expectedindex',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='IndexSwap',
        ),
        migrations.AddField(
            model_name='expectedindex',
            name='myindex',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculate.Myindex'),
        ),
    ]
