# Generated by Django 2.0 on 2018-05-27 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0003_auto_20180527_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedindex',
            name='expectedindex',
            field=models.CharField(max_length=100),
        ),
        migrations.RemoveField(
            model_name='expectedindex',
            name='myindex',
        ),
        migrations.AddField(
            model_name='expectedindex',
            name='myindex',
            field=models.ManyToManyField(to='calculate.Myindex'),
        ),
        migrations.AlterField(
            model_name='myindex',
            name='index',
            field=models.CharField(max_length=100),
        ),
    ]
