# Generated by Django 2.0 on 2018-06-01 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0005_coursecode_indexnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursecode',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
