# Generated by Django 2.0 on 2018-06-01 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0006_auto_20180601_0717'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexnumber',
            name='post',
            field=models.IntegerField(default=0),
        ),
    ]
