# Generated by Django 2.0 on 2018-06-07 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculate', '0007_indexnumber_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('message', models.CharField(max_length=100000)),
            ],
        ),
    ]
